from infospace_executor import InfospaceExecutor


Single_Act_Features_Prompt = {"system": """
SYSTEM / DEVELOPER MESSAGE

You are assisting in Phase 1: latent predicate induction for a single tool.

Your task is not to determine correctness or truth.
Your task is to propose candidate latent predicate schemas that plausibly exist in the semantics of the tool.

A latent predicate schema is:
 - a relation or condition that must have a truth value in the world or execution system
 - that the tool’s success, failure, or behavior depends on
 - even if the agent never explicitly represents it

Inputs may be noisy, partial, or self-generated summaries.
Treat all inputs as fallible evidence, not ground truth.

Important:
 - Prefer procedural / relational predicates over object-existence predicates.
 - Do not invent values, thresholds, coordinates, or episodic facts.
 - Do not assume predicates are correct or enforced.
 - False positives are acceptable at this stage.
""", 

"user": """
We are performing Phase 1 of feature induction for a SINGLE TOOL.

Tool name:
{{$tool_name}}

Inputs (all are optional, incomplete, and fallible):
1) Skill.md (declared intent and usage):
{{$skill_md}}

2) tool_contracts (post-action summaries generated by an LLM):
{{$tool_contracts}}

3) Compressed trace excerpts (selected examples):
{{$trace_excerpts}}

4) Raw tool statistics (optional, aggregated):
{{$statistics}}

Propose a set of LATENT PREDICATE SCHEMAS that plausibly affect the correctness,
applicability, or behavior of THIS TOOL.

Each predicate must describe a **condition, relation, or invariant**, not a one-off fact.

### Required semantic coverage
Your output MUST include predicates from EACH of the following categories
(you may include more):

A) Target resolution & policy interpretation
   (e.g., whether tool modes or policies resolve to concrete actions)

B) Argument / interface interpretation
   (e.g., whether inputs are correctly interpreted or bound)

C) Environmental or world constraints
   (e.g., whether the environment permits the intended action)

D) Tool-internal process or invariants
   (e.g., retry behavior, verification loops, monotonicity assumptions)

### Constraints

- Return at most 8 predicates.
- Do NOT propose generic predicates like “something exists” unless existence
  is the *only* plausible failure mode.
- If a predicate seems “obvious” or normally implicit, still include it.
- If a predicate is violated or contradicted in the traces, that is a reason
  TO include it.
- If two predicates are closely related, list them separately rather than merging.

For EACH predicate, provide:

- name: short, canonical, snake_case
- type: one of precondition / invariant / applicability_constraint
- description: one sentence, non-episodic, relational or procedural
- evidence_sources: one or more of
    [skill_md, tool_contracts, traces, statistics, semantic_necessity]
- notes: optional (especially if evidence is weak, conflicting, or indirect)

Output format:
A JSON array of predicate objects only, in the following format (example values shown):
[
  {
    "name": "snake_case_predicate_name",
    "type": "precondition",
    "description": "one sentence, non-episodic, relational or procedural",
    "evidence_sources": ["tool_contracts"],
    "notes": "optional (especially if evidence is weak, conflicting, or indirect)"
  },
  {
    "name": "observation_verification_consistent",
    "type": "invariant",
    "description": "Post-placement observation accurately reflects whether a placement attempt succeeded.",
    "evidence_sources": ["skill_md", "traces"]
  }
]

Do not include introductory, explanatory, or concluding text outside JSON.
"""}

class Single_Act_Features:
    def __init__(self, executor: InfospaceExecutor, tool_name: str, skill_md: str, tool_contracts: str, trace_excerpts: str, statistics: str):
        self.executor: InfospaceExecutor = executor
        self.tool_name = tool_name
        self.skill_md = skill_md
        self.tool_contracts = tool_contracts
        self.trace_excerpts = trace_excerpts
        self.statistics = statistics
        self.system_prompt = Single_Act_Features_Prompt["system"]
        self.user_prompt = Single_Act_Features_Prompt["user"]

    def generate_features(self) -> str:
        return self.executor.llm_generate([self.system_prompt, self.user_prompt], 
            bindings={"tool_name": self.tool_name, "skill_md": self.skill_md, "tool_contracts": self.tool_contracts, "trace_excerpts": self.trace_excerpts, "statistics": self.statistics},
            max_tokens=1200,
            temperature=0.3,
            stops=["</end>"],
            is_json=True)